### ISSUE TITLE
unexpected behavior while cancelling save of log file, csv

### ISSUE THREAD

**Issue by Xamis** [resfilter/eehack#10]
If you click save, then click cancel on the file save dialog, it pops up the dialog that says log file saved, then you get the discard/cancel dialog.
When clicking  csv, if you then click cancel it gives a could not open file for writing.
this is on linux, have not tested this on windows
This happens in both 4.0 and 4.1

**Comment by Xamis** [comment]
tested it on windows,  it gives a could not open file for writing when cancelling both log saving and csv saving

**Comment by resfilter** [comment]
fixed to be committed shortly

**Comment by resfilter** [comment]
commited this fix, also pulled in your patch for file extensions on linux, despite the bug we discussed on gearhead: https://github.com/resfilter/eehack/commit/05c8266331418ad7d9503af393dda1768ecc7dda
