### ISSUE TITLE
Problem with flashing

### ISSUE THREAD

**Issue by akpz28** [resfilter/eehack#11]
Loading Definition DEVICE=0xF4 MSG=0x0
Loading Definition DEVICE=0xF4 MSG=0x1
Loading Definition DEVICE=0xF4 MSG=0x2
Loading Definition DEVICE=0xF4 MSG=0x3
Loading Definition DEVICE=0xF4 MSG=0x4
Loading Definition DEVICE=0xF4 MSG=0x5
Loading Definition DEVICE=0xF4 MSG=0x6
Loading Definition DEVICE=0xE4 MSG=0x0
Loaded 1014 elements into 8 definitions.
VERSION re-checking, network went online!
VERSION offline status, skipping versioning
Using monotonic reference clock.
EEHack Version 4.51
Current OS : Windows 8
Built with THROTTLE_MS=2
Opened serial port COM3 Description USB Serial Port MFR FTDI
Opened serial port COM3 Description USB Serial Port MFR FTDI
VERSION re-checking, network went online!
VERSION offline status, skipping versioning
VERSION re-checking, network went online!
VERSION offline status, skipping versioning
VERSION re-checking, network went online!
VERSION offline status, skipping versioning
VERSION re-checking, network went online!
VERSION offline status, skipping versioning
SERIAL: ECHO CORRUPT! (bad serial interface?)
SERIAL: WAITED_TOO_LONG in serial_read_packet
SERIAL: No echo!  (Serial interface problem..?)
SERIAL: WAITED_TOO_LONG in serial_read_packet
SERIAL: No echo!  (Serial interface problem..?)
SERIAL: WAITED_TOO_LONG in serial_read_packet
SERIAL: No echo!  (Serial interface problem..?)
SERIAL: WAITED_TOO_LONG in serial_read_packet
SERIAL: No echo!  (Serial interface problem..?)
SERIAL: WAITED_TOO_LONG in serial_read_packet
SERIAL: No echo!  (Serial interface problem..?)
SERIAL: WAITED_TOO_LONG in serial_read_packet
SERIAL: No echo!  (Serial interface problem..?)
SERIAL: WAITED_TOO_LONG in serial_read_packet
SERIAL: No echo!  (Serial interface problem..?)
SERIAL: WAITED_TOO_LONG in serial_read_packet
SERIAL: No echo!  (Serial interface problem..?)
SERIAL: WAITED_TOO_LONG in serial_read_packet
SERIAL: No echo!  (Serial interface problem..?)
Opened serial port COM3 Description USB Serial Port MFR FTDI

**Comment by resfilter** [comment]
hey, what vehicle are you working with?  Can you try the latest beta and select your vehicle type in settings and see if that helps?

**Comment by akpz28** [comment]
94 lt1 camaro, using 4.5.1 eehack window8
