### ISSUE TITLE
Tooltips on main menu

### ISSUE THREAD

**Issue by sherlock9c1** [resfilter/eehack#9]
On the MAIN menu:
Actuator Tooltips are all Power Enrichment.
MAP:  Acelleration should only have one L.
Closed Loop needs a tooltip.

On the FLASH menu:
SECONADRY EEPROM should be SECONDARY EEPROM

**Comment by resfilter** [comment]
Thanks for the feedback, I've fixed those for the next release!  any other feedback is much appreciated
